<?php
if (!defined('ABSPATH')) exit;
function uem_payments_install_tables() { global $wpdb; $table=$wpdb->prefix.'uem_orders'; $charset=$wpdb->get_charset_collate(); require_once ABSPATH.'wp-admin/includes/upgrade.php'; dbDelta("CREATE TABLE {$table} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, order_ref varchar(64) NOT NULL, event_id bigint(20) unsigned NOT NULL, user_id bigint(20) unsigned NOT NULL, ticket_code varchar(100) NOT NULL, amount decimal(10,2) NOT NULL, currency varchar(3) NOT NULL DEFAULT 'RON', provider varchar(40) NOT NULL, provider_transaction_id varchar(100) DEFAULT '', status varchar(30) NOT NULL DEFAULT 'pending', payload longtext NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY (id), UNIQUE KEY order_ref (order_ref), KEY event_user (event_id,user_id), KEY provider_transaction (provider_transaction_id)) {$charset};"); }
add_action('init','uem_payments_install_tables',5);
function uem_payment_encrypt($value){if($value===''||!function_exists('openssl_encrypt'))return ''; $key=hash('sha256',wp_salt('auth'),true);$iv=random_bytes(16);return base64_encode($iv.openssl_encrypt($value,'aes-256-cbc',$key,OPENSSL_RAW_DATA,$iv));}
function uem_payment_decrypt($value){$raw=base64_decode($value,true);if(!$raw||strlen($raw)<17)return '';return openssl_decrypt(substr($raw,16),'aes-256-cbc',hash('sha256',wp_salt('auth'),true),OPENSSL_RAW_DATA,substr($raw,0,16));}
function uem_payment_settings(){return ['mode'=>get_option('uem_payment_mode','sandbox'),'pos_signature'=>get_option('uem_netopia_pos_signature',''),'api_key'=>uem_payment_decrypt(get_option('uem_netopia_api_key',''))];}
function uem_event_ticket_tiers($event_id){$tiers=get_post_meta($event_id,'_uem_ticket_tiers',true);return is_array($tiers)?$tiers:[];}
function uem_active_ticket_tiers($event_id){$now=current_time('timestamp');return array_values(array_filter(uem_event_ticket_tiers($event_id),function($tier)use($now){return !empty($tier['name'])&&(!empty($tier['start'])?strtotime($tier['start'].' 00:00:00')<=$now:true)&&(!empty($tier['end'])?strtotime($tier['end'].' 23:59:59')>=$now:true);}));}
function uem_payment_create_order($event_id,$user_id,$ticket_code){$tier=null;foreach(uem_active_ticket_tiers($event_id)as$item)if(hash_equals((string)($item['code']??''),(string)$ticket_code)){$tier=$item;break;}if(!$tier)return new WP_Error('invalid_ticket','Selected ticket is not available.');global $wpdb;$table=$wpdb->prefix.'uem_orders';$ref='UEM-'.strtoupper(wp_generate_password(18,false,false));$now=current_time('mysql');$wpdb->insert($table,['order_ref'=>$ref,'event_id'=>$event_id,'user_id'=>$user_id,'ticket_code'=>$ticket_code,'amount'=>number_format((float)$tier['price'],2,'.',''),'currency'=>'RON','provider'=>'netopia_v2','status'=>'pending','created_at'=>$now,'updated_at'=>$now]);return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE order_ref=%s",$ref));}
function uem_payment_get_order($ref){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}uem_orders WHERE order_ref=%s",$ref));}
function uem_payment_mark_paid($ref,$transaction,$payload=[]){global $wpdb;$table=$wpdb->prefix.'uem_orders';$order=uem_payment_get_order($ref);if(!$order||$order->status==='paid')return $order;$wpdb->update($table,['status'=>'paid','provider_transaction_id'=>sanitize_text_field($transaction),'payload'=>wp_json_encode($payload),'updated_at'=>current_time('mysql')],['id'=>$order->id]);$attendees=get_post_meta($order->event_id,'_uem_attendees',true)?:[];if(!in_array((int)$order->user_id,$attendees,true)){$attendees[]=(int)$order->user_id;update_post_meta($order->event_id,'_uem_attendees',$attendees);}return $order;}
